import keyMirror from 'keymirror';

export default keyMirror({
  WAREHOUSE_LOAD_COMPLETE: null,
  WAREHOUSE_ITEM_TOGGLE: null,
  WAREHOUSE_PRODUCT_TOGGLE: null,
  WAREHOUSE_EXPAND_NEXT_WAREHOUSE: null,
  WAREHOUSE_REMOVE_SELECTED_PRODUCTS_CURRENT_WAREHOUSE: null,
  WAREHOUSE_MOVE_SELECTED_PRODUCT_TO_WAREHOUSE: null,
  WAREHOUSE_CHANGE_EVENT: null
});
